/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountResponse"];
                        "application/json": components["schemas"]["AccountResponse"];
                        "text/json": components["schemas"]["AccountResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAccountRequest"];
                    "text/json": components["schemas"]["UpdateAccountRequest"];
                    "application/*+json": components["schemas"]["UpdateAccountRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AccountResponse"];
                        "application/json": components["schemas"]["AccountResponse"];
                        "text/json": components["schemas"]["AccountResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeleteAccountRequest"];
                    "text/json": components["schemas"]["DeleteAccountRequest"];
                    "application/*+json": components["schemas"]["DeleteAccountRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                    "text/json": components["schemas"]["ChangePasswordRequest"];
                    "application/*+json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                    "text/json": components["schemas"]["RegisterRequest"];
                    "application/*+json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponse"];
                        "application/json": components["schemas"]["AuthResponse"];
                        "text/json": components["schemas"]["AuthResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExperienceResponse"][];
                        "application/json": components["schemas"]["ExperienceResponse"][];
                        "text/json": components["schemas"]["ExperienceResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExperienceRequest"];
                    "text/json": components["schemas"]["ExperienceRequest"];
                    "application/*+json": components["schemas"]["ExperienceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExperienceResponse"];
                        "application/json": components["schemas"]["ExperienceResponse"];
                        "text/json": components["schemas"]["ExperienceResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiences/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExperienceResponse"];
                        "application/json": components["schemas"]["ExperienceResponse"];
                        "text/json": components["schemas"]["ExperienceResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExperienceRequest"];
                    "text/json": components["schemas"]["ExperienceRequest"];
                    "application/*+json": components["schemas"]["ExperienceRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ExperienceResponse"];
                        "application/json": components["schemas"]["ExperienceResponse"];
                        "text/json": components["schemas"]["ExperienceResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectResponse"][];
                        "application/json": components["schemas"]["ProjectResponse"][];
                        "text/json": components["schemas"]["ProjectResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectRequest"];
                    "text/json": components["schemas"]["ProjectRequest"];
                    "application/*+json": components["schemas"]["ProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectResponse"];
                        "application/json": components["schemas"]["ProjectResponse"];
                        "text/json": components["schemas"]["ProjectResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectResponse"];
                        "application/json": components["schemas"]["ProjectResponse"];
                        "text/json": components["schemas"]["ProjectResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProjectRequest"];
                    "text/json": components["schemas"]["ProjectRequest"];
                    "application/*+json": components["schemas"]["ProjectRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProjectResponse"];
                        "application/json": components["schemas"]["ProjectResponse"];
                        "text/json": components["schemas"]["ProjectResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SkillResponse"][];
                        "application/json": components["schemas"]["SkillResponse"][];
                        "text/json": components["schemas"]["SkillResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SkillRequest"];
                    "text/json": components["schemas"]["SkillRequest"];
                    "application/*+json": components["schemas"]["SkillRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SkillResponse"];
                        "application/json": components["schemas"]["SkillResponse"];
                        "text/json": components["schemas"]["SkillResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/skills/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SkillResponse"];
                        "application/json": components["schemas"]["SkillResponse"];
                        "text/json": components["schemas"]["SkillResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SkillRequest"];
                    "text/json": components["schemas"]["SkillRequest"];
                    "application/*+json": components["schemas"]["SkillRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SkillResponse"];
                        "application/json": components["schemas"]["SkillResponse"];
                        "text/json": components["schemas"]["SkillResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LanguageResponse"][];
                        "application/json": components["schemas"]["LanguageResponse"][];
                        "text/json": components["schemas"]["LanguageResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LanguageRequest"];
                    "text/json": components["schemas"]["LanguageRequest"];
                    "application/*+json": components["schemas"]["LanguageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LanguageResponse"];
                        "application/json": components["schemas"]["LanguageResponse"];
                        "text/json": components["schemas"]["LanguageResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LanguageResponse"];
                        "application/json": components["schemas"]["LanguageResponse"];
                        "text/json": components["schemas"]["LanguageResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LanguageRequest"];
                    "text/json": components["schemas"]["LanguageRequest"];
                    "application/*+json": components["schemas"]["LanguageRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LanguageResponse"];
                        "application/json": components["schemas"]["LanguageResponse"];
                        "text/json": components["schemas"]["LanguageResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/education": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EducationResponse"][];
                        "application/json": components["schemas"]["EducationResponse"][];
                        "text/json": components["schemas"]["EducationResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EducationRequest"];
                    "text/json": components["schemas"]["EducationRequest"];
                    "application/*+json": components["schemas"]["EducationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EducationResponse"];
                        "application/json": components["schemas"]["EducationResponse"];
                        "text/json": components["schemas"]["EducationResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/education/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EducationResponse"];
                        "application/json": components["schemas"]["EducationResponse"];
                        "text/json": components["schemas"]["EducationResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EducationRequest"];
                    "text/json": components["schemas"]["EducationRequest"];
                    "application/*+json": components["schemas"]["EducationRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EducationResponse"];
                        "application/json": components["schemas"]["EducationResponse"];
                        "text/json": components["schemas"]["EducationResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseResponse"][];
                        "application/json": components["schemas"]["CourseResponse"][];
                        "text/json": components["schemas"]["CourseResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CourseRequest"];
                    "text/json": components["schemas"]["CourseRequest"];
                    "application/*+json": components["schemas"]["CourseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseResponse"];
                        "application/json": components["schemas"]["CourseResponse"];
                        "text/json": components["schemas"]["CourseResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseResponse"];
                        "application/json": components["schemas"]["CourseResponse"];
                        "text/json": components["schemas"]["CourseResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CourseRequest"];
                    "text/json": components["schemas"]["CourseRequest"];
                    "application/*+json": components["schemas"]["CourseRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CourseResponse"];
                        "application/json": components["schemas"]["CourseResponse"];
                        "text/json": components["schemas"]["CourseResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfileResponse"][];
                        "application/json": components["schemas"]["ProfileResponse"][];
                        "text/json": components["schemas"]["ProfileResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileRequest"];
                    "text/json": components["schemas"]["ProfileRequest"];
                    "application/*+json": components["schemas"]["ProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfileResponse"];
                        "application/json": components["schemas"]["ProfileResponse"];
                        "text/json": components["schemas"]["ProfileResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfileResponse"];
                        "application/json": components["schemas"]["ProfileResponse"];
                        "text/json": components["schemas"]["ProfileResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileRequest"];
                    "text/json": components["schemas"]["ProfileRequest"];
                    "application/*+json": components["schemas"]["ProfileRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfileResponse"];
                        "application/json": components["schemas"]["ProfileResponse"];
                        "text/json": components["schemas"]["ProfileResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/slug-availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    slug?: string;
                    excludeProfileId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfileItemsResponse"];
                        "application/json": components["schemas"]["ProfileItemsResponse"];
                        "text/json": components["schemas"]["ProfileItemsResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProfileItemsRequest"];
                    "text/json": components["schemas"]["ProfileItemsRequest"];
                    "application/*+json": components["schemas"]["ProfileItemsRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/public/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PublicResumeResponse"];
                        "application/json": components["schemas"]["PublicResumeResponse"];
                        "text/json": components["schemas"]["PublicResumeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AccountResponse: {
            email: string;
            fullName: null | string;
            headline: null | string;
            location: null | string;
            phoneNumber: null | string;
            showEmailOnResume: boolean;
            linkedInUrl: null | string;
            gitHubUrl: null | string;
            websiteUrl: null | string;
        };
        AuthResponse: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        CourseRequest: {
            name: string;
            provider: null | string;
            /** Format: date */
            completionDate: null | string;
            certificateUrl: null | string;
        };
        CourseResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            provider: null | string;
            /** Format: date */
            completionDate: null | string;
            certificateUrl: null | string;
        };
        DeleteAccountRequest: {
            password: string;
        };
        EducationRequest: {
            institution: string;
            degree: string;
            field: null | string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: null | string;
        };
        EducationResponse: {
            /** Format: uuid */
            id: string;
            institution: string;
            degree: string;
            field: null | string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: null | string;
        };
        ExperienceRequest: {
            company: string;
            role: string;
            location: null | string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: null | string;
            description: null | string;
        };
        ExperienceResponse: {
            /** Format: uuid */
            id: string;
            company: string;
            role: string;
            location: null | string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: null | string;
            description: null | string;
        };
        LanguageProficiency: number;
        LanguageRequest: {
            name: string;
            proficiency: components["schemas"]["LanguageProficiency"];
        };
        LanguageResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            proficiency: components["schemas"]["LanguageProficiency"];
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        ProfileItemSelection: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            displayOrder: number | string;
        };
        ProfileItemsRequest: {
            experiences: null | components["schemas"]["ProfileItemSelection"][];
            projects: null | components["schemas"]["ProfileItemSelection"][];
            skills: null | components["schemas"]["ProfileItemSelection"][];
            languages: null | components["schemas"]["ProfileItemSelection"][];
            education: null | components["schemas"]["ProfileItemSelection"][];
            courses: null | components["schemas"]["ProfileItemSelection"][];
        };
        ProfileItemsResponse: {
            experiences: components["schemas"]["ProfileItemSelection"][];
            projects: components["schemas"]["ProfileItemSelection"][];
            skills: components["schemas"]["ProfileItemSelection"][];
            languages: components["schemas"]["ProfileItemSelection"][];
            education: components["schemas"]["ProfileItemSelection"][];
            courses: components["schemas"]["ProfileItemSelection"][];
        };
        ProfileRequest: {
            name: string;
            slug: null | string;
            headline: null | string;
            summary: null | string;
            isPublic: boolean;
            theme: null | string;
            accentColor: null | string;
        };
        ProfileResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            headline: null | string;
            summary: null | string;
            isPublic: boolean;
            theme: string;
            accentColor: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProjectRequest: {
            name: string;
            description: null | string;
            url: null | string;
            repoUrl: null | string;
            /** Format: date */
            date: null | string;
        };
        ProjectResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            description: null | string;
            url: null | string;
            repoUrl: null | string;
            /** Format: date */
            date: null | string;
        };
        PublicOwner: {
            fullName: null | string;
            headline: null | string;
            location: null | string;
            email: null | string;
            phoneNumber: null | string;
            linkedInUrl: null | string;
            gitHubUrl: null | string;
            websiteUrl: null | string;
        };
        PublicResumeResponse: {
            name: string;
            summary: null | string;
            theme: string;
            accentColor: string;
            owner: components["schemas"]["PublicOwner"];
            experiences: components["schemas"]["ExperienceResponse"][];
            projects: components["schemas"]["ProjectResponse"][];
            skills: components["schemas"]["SkillResponse"][];
            languages: components["schemas"]["LanguageResponse"][];
            education: components["schemas"]["EducationResponse"][];
            courses: components["schemas"]["CourseResponse"][];
        };
        RegisterRequest: {
            email: string;
            password: string;
            fullName: null | string;
        };
        SkillCategory: number;
        SkillLevel: number;
        SkillRequest: {
            name: string;
            category: components["schemas"]["SkillCategory"];
            level: components["schemas"]["SkillLevel"];
        };
        SkillResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            category: components["schemas"]["SkillCategory"];
            level: components["schemas"]["SkillLevel"];
        };
        UpdateAccountRequest: {
            fullName: null | string;
            headline: null | string;
            location: null | string;
            phoneNumber: null | string;
            showEmailOnResume: boolean;
            linkedInUrl: null | string;
            gitHubUrl: null | string;
            websiteUrl: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
